# 美股指數

In [1]:
# https://financialmodelingprep.com/api/v3/historical-price-full/%5ERUA?from=1993-01-01&to=2024-10-10&apikey=

In [2]:
import pandas as pd
import requests
import json
import configparser
from sqlalchemy import create_engine

In [3]:
# 資料庫連接設定

# 讀取 config.ini 檔案
config = configparser.ConfigParser()
config.read('../../DB_Processor/config.ini')


# 從 config.ini 中獲取資料庫連接設定
username = config['database']['user']
password = config['database']['password']
database = config['database']['db']
host = config['database']['host']
port = config['database']['port']

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}/{database}')

In [4]:
BASE_URL = 'https://financialmodelingprep.com/api/v3/historical-price-full/'
INDEX = '^RUA'
API_KEY = config['api']['financialmodelingprep_api_key']
START_DATE = '2024-10-11'
END_DATE = '2024-12-31'

In [5]:
url = f'{BASE_URL}{INDEX}?from={START_DATE}&to={END_DATE}&apikey={API_KEY}'

In [6]:
response = requests.get(url)
data = response.json()
historical_data = data['historical']

In [7]:
df = pd.DataFrame(historical_data)
df

,date,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime
0,2024-12-31,3376.72656,3384.28979,3349.81396,3356.82324,3356.82324,0,0,-19.90332,-0.589430,3366.91,"December 31, 24",-0.005894
1,2024-12-30,3379.11011,3388.46997,3347.62988,3370.12988,3370.12988,0,0,-8.98023,-0.265760,3371.33,"December 30, 24",-0.002658
2,2024-12-27,3429.32007,3429.32007,3384.58008,3405.75000,3405.75000,0,0,-23.57007,-0.687310,3412.24,"December 27, 24",-0.006873
3,2024-12-26,3434.16992,3450.27002,3425.87012,3444.79004,3444.79004,0,0,10.62012,0.309250,3438.78,"December 26, 24",0.003093
4,2024-12-24,3412.65991,3444.27002,3411.89990,3444.25000,3444.25000,0,0,31.59009,0.925670,3428.27,"December 24, 24",0.009257
5,2024-12-23,3388.80005,3409.12988,3368.75000,3407.29004,3407.29004,0,0,18.48999,0.545620,3393.49,"December 23, 24",0.005456
6,2024-12-20,3335.95996,3415.05005,3328.62988,3386.80005,3386.80005,0,0,50.84009,1.520000,3366.61,"December 20, 24",0.015200
7,2024-12-19,3372.67993,3390.73999,3349.73999,3350.01001,3350.01001,0,0,-22.66992,-0.672160,3365.79,"December 19, 24",-0.006722
8,2024-12-18,3464.36011,3472.39990,3351.39990,3353.78003,3353.78003,0,0,-110.58008,-3.190000,3410.48,"December 18, 24",-0.031900
9,2024-12-17,3465.10010,3467.73999,3454.89990,3463.04004,3463.04004,0,0,-2.06006,-0.059452,3462.70,"December 17, 24",-0.000595
10,2024-12-16,3472.93994,3486.80005,3471.76001,3480.08008,3480.08008,0,0,7.14014,0.205590,3477.90,"December 16, 24",0.002056
11,2024-12-13,3468.97998,3481.86011,3457.32007,3466.19995,3466.19995,0,0,-2.78003,-0.080140,3468.59,"December 13, 24",-0.000801
12,2024-12-12,3483.43994,3485.47998,3468.38989,3468.38989,3468.38989,0,0,-15.05005,-0.432050,3476.42,"December 12, 24",-0.004320
13,2024-12-11,3475.60010,3493.98999,3475.60010,3488.85010,3488.85010,0,0,13.25000,0.381230,3483.51,"December 11, 24",0.003812
14,2024-12-10,3477.69995,3478.46997,3457.79004,3460.19995,3460.19995,0,0,-17.50000,-0.503210,3468.54,"December 10, 24",-0.005032
15,2024-12-09,3494.52002,3497.85010,3471.73999,3473.35010,3473.35010,0,0,-21.16992,-0.605800,3484.37,"December 09, 24",-0.006058
16,2024-12-06,3493.47998,3502.03003,3491.73999,3497.78003,3497.78003,0,0,4.30005,0.123090,3496.26,"December 06, 24",0.001231
17,2024-12-05,3498.77002,3500.07007,3486.14990,3487.25000,3487.25000,0,0,-11.52002,-0.329260,3493.06,"December 05, 24",-0.003293
18,2024-12-04,3481.86011,3498.78003,3481.86011,3497.72998,3497.72998,0,0,15.86987,0.455790,3490.06,"December 04, 24",0.004558
19,2024-12-03,3473.65991,3475.53003,3465.47998,3474.19995,3474.19995,0,0,0.54004,0.015547,3472.22,"December 03, 24",0.000155
20,2024-12-02,3470.13989,3477.67993,3466.73999,3473.73999,3473.73999,0,0,3.60010,0.103750,3472.07,"December 02, 24",0.001038
21,2024-11-29,3452.01001,3474.18994,3452.01001,3466.85010,3466.85010,0,0,14.84009,0.429900,3461.27,"November 29, 24",0.004299
22,2024-11-27,3463.48999,3463.93994,3441.96997,3449.54004,3449.54004,0,0,-13.94995,-0.402770,3454.73,"November 27, 24",-0.004028
23,2024-11-26,3448.32007,3463.38989,3446.36011,3461.48999,3461.48999,0,0,13.16992,0.381920,3454.89,"November 26, 24",0.003819
24,2024-11-25,3439.77002,3464.64990,3435.47998,3447.22998,3447.22998,0,0,7.45996,0.216870,3446.78,"November 25, 24",0.002169
25,2024-11-22,3413.78003,3433.84009,3413.78003,3432.02002,3432.02002,0,0,18.23999,0.534300,3423.36,"November 22, 24",0.005343
26,2024-11-21,3395.97998,3421.87012,3379.20996,3413.66992,3413.66992,0,0,17.68994,0.520910,3402.68,"November 21, 24",0.005209
27,2024-11-20,3387.63989,3391.97998,3358.64990,3390.61011,3390.61011,0,0,2.97022,0.087678,3382.22,"November 20, 24",0.000877
28,2024-11-19,3365.71997,3391.26001,3352.07007,3388.81006,3388.81006,0,0,23.09009,0.686040,3374.47,"November 19, 24",0.006860
29,2024-11-18,3360.98999,3381.97998,3358.22998,3373.47998,3373.47998,0,0,12.48999,0.371620,3368.67,"November 18, 24",0.003716
30,2024-11-15,3392.87988,3392.87988,3350.36011,3360.01001,3360.01001,0,0,-32.86987,-0.968790,3374.03,"November 15, 24",-0.009688
31,2024-11-14,3429.84009,3433.45996,3401.39990,3404.89990,3404.89990,0,0,-24.94019,-0.727150,3417.40,"November 14, 24",-0.007272
32,2024-11-13,3432.76001,3444.78003,3423.55005,3428.28003,3428.28003,0,0,-4.47998,-0.130510,3432.34,"November 13, 24",-0.001305
33,2024-11-12,3441.19995,3446.98999,3416.98999,3430.25000,3430.25000,0,0,-10.94995,-0.318200,3433.86,"November 12, 24",-0.003182
34,2024-11-11,3435.85010,3450.73999,3435.68994,3443.76001,3443.76001,0,0,7.90991,0.230220,3441.51,"November 11, 24",0.002302
35,2024-11-08,3419.82007,3441.36011,3419.82007,3433.03003,3433.03003,0,0,13.20996,0.386280,3428.51,"November 08, 24",0.003863
36,2024-11-07,3400.30005,3425.48999,3400.30005,3418.68994,3418.68994,0,0,18.38989,0.540830,3411.20,"November 07, 24",0.005408
37,2024-11-06,3325.91992,3398.71997,3325.91992,3395.36011,3395.36011,0,0,69.44019,2.090000,3361.48,"November 06, 24",0.020900
38,2024-11-05,3264.37012,3302.85010,3264.37012,3302.64990,3302.64990,0,0,38.27978,1.170000,3283.56,"November 05, 24",0.011700
39,2024-11-04,3265.44995,3275.94995,3252.36011,3260.37012,3260.37012,0,0,-5.07983,-0.155560,3263.53,"November 04, 24",-0.001556
40,2024-11-01,3252.94995,3292.90991,3252.94995,3267.78003,3267.78003,0,0,14.83008,0.455900,3266.65,"November 01, 24",0.004559
41,2024-10-31,3300.88989,3300.88989,3254.12012,3254.84009,3254.84009,0,0,-46.04980,-1.400000,3277.69,"October 31, 24",-0.014000
42,2024-10-30,3329.98999,3336.12988,3313.32007,3314.37012,3314.37012,0,0,-15.61987,-0.469070,3323.45,"October 30, 24",-0.004691
43,2024-10-29,3315.67993,3330.63989,3305.62988,3324.00000,3324.00000,0,0,8.32007,0.250930,3318.99,"October 29, 24",0.002509
44,2024-10-28,3318.17993,3328.75000,3318.17993,3319.11011,3319.11011,0,0,0.93018,0.028033,3321.05,"October 28, 24",0.000280
45,2024-10-25,3316.75000,3337.52002,3301.94995,3306.14990,3306.14990,0,0,-10.60010,-0.319590,3315.59,"October 25, 24",-0.003196
46,2024-10-24,3303.51001,3313.59009,3295.12012,3309.15991,3309.15991,0,0,5.64990,0.171030,3305.35,"October 24, 24",0.001710
47,2024-10-23,3322.52002,3322.52002,3281.33008,3301.27002,3301.27002,0,0,-21.25000,-0.639570,3306.91,"October 23, 24",-0.006396
48,2024-10-22,3324.50000,3337.16992,3316.88989,3330.92993,3330.92993,0,0,6.42993,0.193410,3327.37,"October 22, 24",0.001934
49,2024-10-21,3342.28003,3344.21997,3319.43994,3334.19995,3334.19995,0,0,-8.08008,-0.241750,3335.03,"October 21, 24",-0.002417
50,2024-10-18,3341.35010,3348.86011,3335.94995,3344.79004,3344.79004,0,0,3.43994,0.102950,3342.74,"October 18, 24",0.001030
51,2024-10-17,3348.66992,3352.30005,3331.68994,3332.45996,3332.45996,0,0,-16.20996,-0.484070,3341.28,"October 17, 24",-0.004841
52,2024-10-16,3321.40991,3335.55005,3313.86011,3333.37988,3333.37988,0,0,11.96997,0.360390,3326.05,"October 16, 24",0.003604
53,2024-10-15,3339.12012,3342.83008,3310.81006,3315.40991,3315.40991,0,0,-23.71021,-0.710070,3327.04,"October 15, 24",-0.007101
54,2024-10-14,3321.13989,3343.60010,3321.13989,3337.90991,3337.90991,0,0,16.77002,0.504950,3330.95,"October 14, 24",0.005050
55,2024-10-11,3286.42993,3316.10010,3286.42993,3313.16992,3313.16992,0,0,26.73999,0.813650,3300.53,"October 11, 24",0.008136

In [8]:
df = df[['date', 'open', 'high', 'low', 'close']]
df

          date        open        high         low       close
0   2024-12-31  3376.72656  3384.28979  3349.81396  3356.82324
1   2024-12-30  3379.11011  3388.46997  3347.62988  3370.12988
2   2024-12-27  3429.32007  3429.32007  3384.58008  3405.75000
3   2024-12-26  3434.16992  3450.27002  3425.87012  3444.79004
4   2024-12-24  3412.65991  3444.27002  3411.89990  3444.25000
5   2024-12-23  3388.80005  3409.12988  3368.75000  3407.29004
6   2024-12-20  3335.95996  3415.05005  3328.62988  3386.80005
7   2024-12-19  3372.67993  3390.73999  3349.73999  3350.01001
8   2024-12-18  3464.36011  3472.39990  3351.39990  3353.78003
9   2024-12-17  3465.10010  3467.73999  3454.89990  3463.04004
10  2024-12-16  3472.93994  3486.80005  3471.76001  3480.08008
11  2024-12-13  3468.97998  3481.86011  3457.32007  3466.19995
12  2024-12-12  3483.43994  3485.47998  3468.38989  3468.38989
13  2024-12-11  3475.60010  3493.98999  3475.60010  3488.85010
14  2024-12-10  3477.69995  3478.46997  3457.79004  3460.19995
15  2024-12-09  3494.52002  3497.85010  3471.73999  3473.35010
16  2024-12-06  3493.47998  3502.03003  3491.73999  3497.78003
17  2024-12-05  3498.77002  3500.07007  3486.14990  3487.25000
18  2024-12-04  3481.86011  3498.78003  3481.86011  3497.72998
19  2024-12-03  3473.65991  3475.53003  3465.47998  3474.19995
20  2024-12-02  3470.13989  3477.67993  3466.73999  3473.73999
21  2024-11-29  3452.01001  3474.18994  3452.01001  3466.85010
22  2024-11-27  3463.48999  3463.93994  3441.96997  3449.54004
23  2024-11-26  3448.32007  3463.38989  3446.36011  3461.48999
24  2024-11-25  3439.77002  3464.64990  3435.47998  3447.22998
25  2024-11-22  3413.78003  3433.84009  3413.78003  3432.02002
26  2024-11-21  3395.97998  3421.87012  3379.20996  3413.66992
27  2024-11-20  3387.63989  3391.97998  3358.64990  3390.61011
28  2024-11-19  3365.71997  3391.26001  3352.07007  3388.81006
29  2024-11-18  3360.98999  3381.97998  3358.22998  3373.47998
30  2024-11-15  3392.87988  3392.87988  3350.36011  3360.01001
31  2024-11-14  3429.84009  3433.45996  3401.39990  3404.89990
32  2024-11-13  3432.76001  3444.78003  3423.55005  3428.28003
33  2024-11-12  3441.19995  3446.98999  3416.98999  3430.25000
34  2024-11-11  3435.85010  3450.73999  3435.68994  3443.76001
35  2024-11-08  3419.82007  3441.36011  3419.82007  3433.03003
36  2024-11-07  3400.30005  3425.48999  3400.30005  3418.68994
37  2024-11-06  3325.91992  3398.71997  3325.91992  3395.36011
38  2024-11-05  3264.37012  3302.85010  3264.37012  3302.64990
39  2024-11-04  3265.44995  3275.94995  3252.36011  3260.37012
40  2024-11-01  3252.94995  3292.90991  3252.94995  3267.78003
41  2024-10-31  3300.88989  3300.88989  3254.12012  3254.84009
42  2024-10-30  3329.98999  3336.12988  3313.32007  3314.37012
43  2024-10-29  3315.67993  3330.63989  3305.62988  3324.00000
44  2024-10-28  3318.17993  3328.75000  3318.17993  3319.11011
45  2024-10-25  3316.75000  3337.52002  3301.94995  3306.14990
46  2024-10-24  3303.51001  3313.59009  3295.12012  3309.15991
47  2024-10-23  3322.52002  3322.52002  3281.33008  3301.27002
48  2024-10-22  3324.50000  3337.16992  3316.88989  3330.92993
49  2024-10-21  3342.28003  3344.21997  3319.43994  3334.19995
50  2024-10-18  3341.35010  3348.86011  3335.94995  3344.79004
51  2024-10-17  3348.66992  3352.30005  3331.68994  3332.45996
52  2024-10-16  3321.40991  3335.55005  3313.86011  3333.37988
53  2024-10-15  3339.12012  3342.83008  3310.81006  3315.40991
54  2024-10-14  3321.13989  3343.60010  3321.13989  3337.90991
55  2024-10-11  3286.42993  3316.10010  3286.42993  3313.16992

In [9]:
csv_path = f'../data/US_data/index_data/russell3000_index_{START_DATE}_{END_DATE}.csv'
df.to_csv(csv_path, index=False)

In [10]:
data_df = pd.read_csv(csv_path)

In [11]:
data_df.sort_values(by='date', inplace=True)

In [12]:
data_df

          date        open        high         low       close
55  2024-10-11  3286.42993  3316.10010  3286.42993  3313.16992
54  2024-10-14  3321.13989  3343.60010  3321.13989  3337.90991
53  2024-10-15  3339.12012  3342.83008  3310.81006  3315.40991
52  2024-10-16  3321.40991  3335.55005  3313.86011  3333.37988
51  2024-10-17  3348.66992  3352.30005  3331.68994  3332.45996
50  2024-10-18  3341.35010  3348.86011  3335.94995  3344.79004
49  2024-10-21  3342.28003  3344.21997  3319.43994  3334.19995
48  2024-10-22  3324.50000  3337.16992  3316.88989  3330.92993
47  2024-10-23  3322.52002  3322.52002  3281.33008  3301.27002
46  2024-10-24  3303.51001  3313.59009  3295.12012  3309.15991
45  2024-10-25  3316.75000  3337.52002  3301.94995  3306.14990
44  2024-10-28  3318.17993  3328.75000  3318.17993  3319.11011
43  2024-10-29  3315.67993  3330.63989  3305.62988  3324.00000
42  2024-10-30  3329.98999  3336.12988  3313.32007  3314.37012
41  2024-10-31  3300.88989  3300.88989  3254.12012  3254.84009
40  2024-11-01  3252.94995  3292.90991  3252.94995  3267.78003
39  2024-11-04  3265.44995  3275.94995  3252.36011  3260.37012
38  2024-11-05  3264.37012  3302.85010  3264.37012  3302.64990
37  2024-11-06  3325.91992  3398.71997  3325.91992  3395.36011
36  2024-11-07  3400.30005  3425.48999  3400.30005  3418.68994
35  2024-11-08  3419.82007  3441.36011  3419.82007  3433.03003
34  2024-11-11  3435.85010  3450.73999  3435.68994  3443.76001
33  2024-11-12  3441.19995  3446.98999  3416.98999  3430.25000
32  2024-11-13  3432.76001  3444.78003  3423.55005  3428.28003
31  2024-11-14  3429.84009  3433.45996  3401.39990  3404.89990
30  2024-11-15  3392.87988  3392.87988  3350.36011  3360.01001
29  2024-11-18  3360.98999  3381.97998  3358.22998  3373.47998
28  2024-11-19  3365.71997  3391.26001  3352.07007  3388.81006
27  2024-11-20  3387.63989  3391.97998  3358.64990  3390.61011
26  2024-11-21  3395.97998  3421.87012  3379.20996  3413.66992
25  2024-11-22  3413.78003  3433.84009  3413.78003  3432.02002
24  2024-11-25  3439.77002  3464.64990  3435.47998  3447.22998
23  2024-11-26  3448.32007  3463.38989  3446.36011  3461.48999
22  2024-11-27  3463.48999  3463.93994  3441.96997  3449.54004
21  2024-11-29  3452.01001  3474.18994  3452.01001  3466.85010
20  2024-12-02  3470.13989  3477.67993  3466.73999  3473.73999
19  2024-12-03  3473.65991  3475.53003  3465.47998  3474.19995
18  2024-12-04  3481.86011  3498.78003  3481.86011  3497.72998
17  2024-12-05  3498.77002  3500.07007  3486.14990  3487.25000
16  2024-12-06  3493.47998  3502.03003  3491.73999  3497.78003
15  2024-12-09  3494.52002  3497.85010  3471.73999  3473.35010
14  2024-12-10  3477.69995  3478.46997  3457.79004  3460.19995
13  2024-12-11  3475.60010  3493.98999  3475.60010  3488.85010
12  2024-12-12  3483.43994  3485.47998  3468.38989  3468.38989
11  2024-12-13  3468.97998  3481.86011  3457.32007  3466.19995
10  2024-12-16  3472.93994  3486.80005  3471.76001  3480.08008
9   2024-12-17  3465.10010  3467.73999  3454.89990  3463.04004
8   2024-12-18  3464.36011  3472.39990  3351.39990  3353.78003
7   2024-12-19  3372.67993  3390.73999  3349.73999  3350.01001
6   2024-12-20  3335.95996  3415.05005  3328.62988  3386.80005
5   2024-12-23  3388.80005  3409.12988  3368.75000  3407.29004
4   2024-12-24  3412.65991  3444.27002  3411.89990  3444.25000
3   2024-12-26  3434.16992  3450.27002  3425.87012  3444.79004
2   2024-12-27  3429.32007  3429.32007  3384.58008  3405.75000
1   2024-12-30  3379.11011  3388.46997  3347.62988  3370.12988
0   2024-12-31  3376.72656  3384.28979  3349.81396  3356.82324

In [13]:
data_df.to_sql('rua', con=engine, if_exists='append', index=False)

56